name: Build release

on:
  release:
    types: [released]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CR_BOT_BASIC_TOKEN }}
      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags
      - name: Unset header
        # checkout adds a header that makes branch protection report errors
        # because the Github action bot is not a collaborator on the repo
        run: git config --local --unset http.https://github.com/.extraheader
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn
      - name: Build
        run: yarn build -p never
        env:
          CSC_LINK: ${{ secrets.MACOS_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          appleId: ${{ secrets.APPLE_ID }}
          appleIdPassword: ${{ secrets.APPLE_ID_APP_SPECIFIC_PASSWORD }}
      - name: Upload build to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.CR_BOT_BASIC_TOKEN }}
