name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Type check
        run: yarn tc
      - name: Run tests
        run: yarn test
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn auto shipit
