name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Type check
        run: yarn tc
      - name: Run tests
        run: yarn test:react
