name: Update docs

on:
  push:
    branches:
      - 'main'
      - 'publish-docs'
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Move to docs
        run: cd docs/
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn gatsby build --prefix-paths
      - name: ls
        run: ls public/
      - name: Publish
        run: yarn gh-pages -d public
