name: Create public release

on:
  push
  # workflow_run:
  #   workflows: [Build release]
  #   types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get latest release
        id: latest_release
        run: |
          release=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"\
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          echo "::set-output name=release::release"
      - name: Create public release
        env:
          PUBLIC_REPO_OWNER: akwok-dfci
          PUBLIC_REPO_NAME: clinical-regex-releases
          RELEASE: ${{ steps.latest_release.outputs.release }}
          GH_TOKEN_PUBLIC: ${{ secrets.GH_TOKEN_PUBLIC_RELEASES }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $RELEASE
