name: Create public release

on:
  workflow_run:
    workflows: [Build release]
    types: [completed]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/github-script@v6
        name: Get latest release
        id: latest_release
        with:
          script: |
            return await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

      - uses: actions/github-script@v6
        name: Create public release
        env:
          PUBLIC_REPO_OWNER: lindvalllab 
          PUBLIC_REPO_NAME: clinical-regex-releases
          RELEASE: ${{ steps.latest_release.outputs.result }}
        with:
          github-token: ${{ secrets.GH_TOKEN_PUBLIC_RELEASES }}
          script: |
            const { PUBLIC_REPO_OWNER, PUBLIC_REPO_NAME } = process.env
            let { RELEASE } = process.env

            RELEASE = JSON.parse(RELEASE).data;

            const publicRelease = await github.rest.repos.createRelease({
              owner: PUBLIC_REPO_OWNER,
              repo: PUBLIC_REPO_NAME,
              tag_name: RELEASE.tag_name,
              name: RELEASE.name,
              body: RELEASE.body,
            });

            for (const asset of RELEASE.assets) {
              // https://github.com/octokit/rest.js/issues/6#issuecomment-477800969
              const response = await github.rest.repos.getReleaseAsset({
                headers: {
                  Accept: 'application/octet-stream'
                },
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: asset.id,
              });
              github.rest.repos.uploadReleaseAsset({
                owner: PUBLIC_REPO_OWNER,
                repo: PUBLIC_REPO_NAME,
                release_id: publicRelease.data.id,
                name: asset.name,
                data: response.data
              });
            }
