name: Create public release

on:
  push
  # workflow_run:
  #   workflows: [Build release]
  #   types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/github-script@v6
        name: Get latest release
        id: get_latest_release
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            console.log(release);

            return release;

      - uses: actions/github-script@v6
        name: Create public release
        env:
          PUBLIC_REPO_OWNER: akwok-dfci
          PUBLIC_REPO_NAME: clinical-regex-releases
          RELEASE: ${{ steps.get_latest_release.outputs.result }}
        with:
          github-token: ${{ secrets.GH_TOKEN_PUBLIC_RELEASES }}
          script: |
            const { PUBLIC_REPO_OWNER, PUBLIC_REPO_NAME } = process.env
            let { RELEASE } = process.env

            RELEASE = JSON.parse(RELEASE).data;

            RELEASE.assets.forEach((asset) => {
              console.log(asset)
            })
